# Generated by Django 5.2.5 on 2025-08-27 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryModel',
            new_name='BlogCategoryModel',
        ),
    ]
